version: '3.8'

services:
  client:
    build:
      context: ./client
      target: development
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "3000:3000"

  server:
    build:
      context: ./server
      target: development
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    ports:
      - "3001:3001"
      - "9229:9229"  # For debugging
    command: npm run dev

  cassandra:
    ports:
      - "9042:9042"
    volumes:
      - cassandra_data:/var/lib/cassandra
    environment:
      - MAX_HEAP_SIZE=512M
      - HEAP_NEWSIZE=128M

  redis:
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

volumes:
  cassandra_data:
  redis_data: 